name: 📚 Documentation
description: Report documentation issues or suggest improvements
title: "[Docs]: "
labels: ["documentation", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect documentation
        - Unclear documentation
        - Outdated documentation
        - Documentation improvement
        - New documentation request
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation located?
      placeholder: "docs/api/rest-api.md or https://..."
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: What's wrong with the current documentation?
      placeholder: Describe the issue
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: What should it say instead?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Documentation Category
      description: What area does this relate to?
      options:
        - Getting Started
        - Architecture
        - API Reference
        - Developer Guide
        - Code Navigation
        - Quality Gates
        - Deployment
        - Security
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Screenshots, links, examples, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for similar documentation issues
          required: true
        - label: I have provided the documentation location
          required: true
        - label: I have described the issue clearly
          required: true
